In [1]:
import pandas as pd
netflix_movies=pd.read_csv("/home/dul/netflix_movies.csv")
netflix_movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [2]:
# To sort the values in the country column
# To see only the country value and index
netflix_movies.country.sort_values()

532     Argentina
6210    Argentina
4075    Argentina
398     Argentina
4422    Argentina
          ...
6170          NaN
6195          NaN
6199          NaN
6228          NaN
6231          NaN
Name: country, Length: 6234, dtype: object

In [4]:
# Another way to sort the values in the country column
# To see only the country value and index
# To sort in ascending order
netflix_movies['country'].sort_values()

532     Argentina
6210    Argentina
4075    Argentina
398     Argentina
4422    Argentina
          ...
6170          NaN
6195          NaN
6199          NaN
6228          NaN
6231          NaN
Name: country, Length: 6234, dtype: object

In [5]:
# to view the dataframe as a whole and not only the sorted
netflix_movies.sort_values('country')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
532,81105406,TV Show,Monzón: A Knockout Blow,NaN,"Jorge Román, Mauricio Paniagua, Carla Quevedo,...",Argentina,"October 25, 2019",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",This dramatization tells the story of Argentin...
6210,80239700,TV Show,Psiconautas,NaN,"Guillermo Toledo, Gabriel Goity, Florencia Peñ...",Argentina,"April 15, 2018",2016,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",A Spanish con man masquerades as a therapist a...
4075,80156767,Movie,La Última Fiesta,"Leandro Mark, Nicolás Silbert","Nicolás Vázquez, Alan Sabbagh, Benjamín Amadeo...",Argentina,"February 1, 2017",2016,TV-MA,104 min,"Comedies, International Movies",Three best buddies are thrown into a wild chas...
398,80190990,Movie,Todo Sobre El Asado,"Mariano Cohn, Gastón Duprat",El Negro Álvarez,Argentina,"September 1, 2017",2016,TV-14,86 min,"Documentaries, International Movies",This quirky examination of Argentina's culture...
4422,80142140,Movie,Daemonium,Pablo Parés,"Walter Cornás, Dany Casco, Caro Angus, Rocío R...",Argentina,"December 20, 2016",2015,NR,115 min,"Action & Adventure, Horror Movies, Internation...",In a realm where magic and technology intersec...
...,...,...,...,...,...,...,...,...,...,...,...,...
6170,80136456,TV Show,Age of Glory,NaN,"Debbie Goh, Aenie Wong, Frederick Lee, Leslie ...",NaN,"August 14, 2017",2010,TV-PG,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Amid the thriving nightlife of 1960s Kuala Lum...
6195,80136790,TV Show,Goodnight DJ 1,NaN,"Chan Fong, Z-Chen, Frederick Lee, Melvin Sia, ...",NaN,"April 27, 2018",2016,TV-14,2 Seasons,"International TV Shows, TV Dramas, TV Horror",Young radio announcers from varying background...
6199,80244228,TV Show,Beauty and the Bitches,NaN,"Methinee Kingpayome, Son Songpaisarn, Yingying...",NaN,"April 23, 2019",2016,TV-14,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Beauty pageant contestants from all over Thail...
6228,80159925,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...

In [6]:
# sort values is a series method
type(netflix_movies['title'].sort_values())

pandas.core.series.Series

In [8]:
# To sort descending manner
netflix_movies['country'].sort_values(ascending=False)

4003    West Germany
437          Vietnam
171          Vietnam
4826         Vietnam
117          Vietnam
            ...
6170             NaN
6195             NaN
6199             NaN
6228             NaN
6231             NaN
Name: country, Length: 6234, dtype: object

In [10]:
# when sorting symbools, numbers come before aplhabetic aharacters
netflix_movies.sort_values('title')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5462,81087095,Movie,#Roxy,Michael Kennedy,"Jake Short, Sarah Fisher, Booboo Stewart, Dann...",Canada,"April 10, 2019",2018,TV-14,105 min,"Comedies, Romantic Movies",A teenage hacker with a huge nose helps a cool...
4699,80147908,Movie,#Rucker50,Robert McCullough Jr.,NaN,United States,"December 1, 2016",2016,TV-PG,56 min,"Documentaries, Sports Movies",This documentary celebrates the 50th anniversa...
2693,81092768,Movie,#Selfie,Cristina Jacob,"Flavia Hojda, Crina Semciuc, Olimpia Melinte, ...",Romania,"June 1, 2019",2014,TV-MA,125 min,"Comedies, Dramas, International Movies","Two days before their final exams, three teen ..."
2694,81092766,Movie,#Selfie 69,Cristina Jacob,"Maia Morgenstern, Olimpia Melinte, Crina Semci...",Romania,"June 1, 2019",2016,TV-MA,119 min,"Comedies, Dramas, International Movies","After a painful breakup, a trio of party-lovin..."
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6086,80990464,TV Show,忍者ハットリくん,NaN,NaN,Japan,"December 23, 2018",2012,TV-Y7,2 Seasons,"Anime Series, Kids' TV","Hailing from the mountains of Iga, Kanzo Hatto..."
5281,80136789,TV Show,海的儿子,NaN,"Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,"April 27, 2018",2016,TV-PG,1 Season,"International TV Shows, TV Dramas","Two brothers start a new life in Singapore, wh..."
3904,80226338,TV Show,마녀사냥,NaN,"Si-kyung Sung, Se-yoon Yoo, Dong-yup Shin, Ji-...",South Korea,"February 19, 2018",2015,TV-MA,1 Season,"International TV Shows, Korean TV Shows, Stand...",Four Korean celebrity men and guest stars of b...
3799,80226357,Movie,반드시 잡는다,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...
355,81011096,Movie,최강전사 미니특공대 : 영웅의 탄생,Young Jun Lee,"Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...",NaN,"September 1, 2018",2018,TV-Y7-FV,68 min,Children & Family Movies,"Miniforce, a special task force of elite range..."

In [11]:
netflix_movies.country.order()
# the depracated methods not working now

AttributeError: 'Series' object has no attribute 'order'

In [12]:
# sort of by two columns
# first sort by country column, then sort by title column
netflix_movies.sort_values(['country','title'])

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1834,80241044,Movie,"27, el club de los malditos",Nicanor Loreti,"Diego Capusotto, Sofía Gala, Daniel Aráoz, Wil...",Argentina,"May 1, 2018",2018,TV-MA,82 min,"Action & Adventure, Comedies, International Mo...",After a musician dies under suspicious circums...
4851,80115152,Movie,Abzurdah,Daniela Goggi,"Eugenia Suárez, Esteban Lamothe, Gloria Carrá,...",Argentina,"August 25, 2016",2015,TV-MA,90 min,"Dramas, International Movies",A disenfranchised 16-year-old girl connects to...
3925,80191555,Movie,Agustín Aristarán: Soy Rada,Mariano Baez,Agustín Aristarán,Argentina,"February 16, 2018",2018,TV-MA,60 min,Stand-Up Comedy,"Argentine comedian Agustín ""Radagast"" Aristará..."
4957,81106517,TV Show,Apache: The Life of Carlos Tevez,NaN,"Balthazar Murillo, Vanesa González, Alberto Aj...",Argentina,"August 16, 2019",2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",This gritty dramatization of the life of Carlo...
3321,80149575,Movie,Caida del Cielo,Néstor Sánchez Sotelo,"Muriel Santa Ana, Peto Menahem, Héctor Díaz, S...",Argentina,"January 20, 2017",2016,NR,78 min,"Comedies, International Movies, Romantic Movies",When Julia literally falls into Alejandro's ba...
...,...,...,...,...,...,...,...,...,...,...,...,...
5973,81100135,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
1434,81170694,Movie,Zoé: Panoramas,"Rodrigo Guardiola, Gabriel Cruz Rivas","Sergio Acosta, Jesús Báez, Ángel Mosqueda, Rod...",NaN,"November 1, 2019",2016,TV-14,89 min,"Documentaries, International Movies, Music & M...",This introspective rockumentary follows the ca...
2030,80993794,TV Show,แผนร้ายนายเจ้าเล่ห์,NaN,"Chutavuth Pattarakampol, Sheranut Yusananda, N...",NaN,"March 30, 2019",2016,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...","When two brothers fall for two sisters, they q..."
5281,80136789,TV Show,海的儿子,NaN,"Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,"April 27, 2018",2016,TV-PG,1 Season,"International TV Shows, TV Dramas","Two brothers start a new life in Singapore, wh..."
355,81011096,Movie,최강전사 미니특공대 : 영웅의 탄생,Young Jun Lee,"Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...",NaN,"September 1, 2018",2018,TV-Y7-FV,68 min,Children & Family Movies,"Miniforce, a special task force of elite range..."